### ISSUE TITLE
EDD Orders not created when using Gravity Forms Stripe Payment Form 

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/edd-gravity-forms-checkout#5]
Expected:
When order is created in Gravity Forms, order should be created in EDD

Actual:
Works when using "Gravity Forms Create Card Fields" but doesn't work when using "Stripe Payment Form (Stripe Checkout, SCA-ready)".

![Screen Shot 2019-10-14 at 3 18 54 PM](https://user-images.githubusercontent.com/30910807/66780237-f5082400-ee95-11e9-9e3d-4551bb46fb30.png)

It appears the Gravity Forms extension needs to be updated to support this Payment Method.

Gravity Forms: 2.4.14
Gravity Forms Stripe Add-On: 3.2
EDD - Gravity Forms Checkout: 1.5.1

Tested on customer site and internal local site.
https://secure.helpscout.net/conversation/971279117/133343?folderId=1847242

**Comment by cklosowski** [comment]
@mintplugins I can get this to you, we have copies of it all.

**Comment by dgoldak** [comment]
@cklosowski I hooked him up yesterday.

**Comment by cklosowski** [comment]
thanks @dgoldak

**Comment by nutsandbolts** [comment]
Tested `issue/5` and confirmed it works.

**Comment by dgoldak** [comment]
Confirm `issue/5` is working! 

Nice work @mintplugins !
